from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('mbti', models.CharField(blank=True, max_length=10)),
                ('interests', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_preference', models.CharField(choices=[('remote','Remote'),('onsite','On-site'),('hybrid','Hybrid')], default='hybrid', max_length=20)),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_role', models.CharField(blank=True, max_length=200)),
                ('business_industry', models.CharField(blank=True, max_length=200)),
                ('business_description', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('behance', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('calendly', models.URLField(blank=True)),
                ('theme_color', models.CharField(default='#7c6af7', max_length=7)),
                ('dark_mode', models.BooleanField(default=True)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile')),
            ],
            options={'ordering': ['-start_date']},
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=80)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
            ],
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('emoji', models.CharField(default='🚀', max_length=5)),
                ('status', models.CharField(choices=[('live','Live'),('wip','In Progress'),('planned','Planned'),('completed','Completed')], default='completed', max_length=20)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('looking_for_collaborators', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.profile')),
            ],
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🛠️', max_length=5)),
                ('category', models.CharField(choices=[('design','Design'),('dev','Development'),('productivity','Productivity'),('hardware','Hardware'),('other','Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='profiles.profile')),
            ],
            options={'ordering': ['category', 'order']},
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.IntegerField(choices=[(20,'Basic'),(40,'Elementary'),(60,'Intermediate'),(80,'Advanced'),(100,'Native')], default=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile')),
            ],
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin','LinkedIn'),('github','GitHub'),('behance','Behance'),('dribbble','Dribbble'),('twitter','Twitter/X'),('instagram','Instagram'),('youtube','YouTube'),('tiktok','TikTok'),('telegram','Telegram'),('discord','Discord'),('patreon','Patreon'),('other','Other')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profiles.profile')),
            ],
            options={'ordering': ['order']},
        ),
    ]
